# Replace these with the actual credentials
repoUsername=ashish.gupta@sign3labs.com
repoPassword=Sign3labs@1234
repoUrl=https://sign3.jfrog.io/artifactory/intelligence-test-local/
#repoUrl="https://sign3.jfrog.io/artifactory/intelligence-generic-local/"